name: Deploy to GitHub Pages

on:
  push:
    branches: 
      - svelte-refactor

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Check for CNAME file
        id: check-cname
        run: |
          if [ -f "CNAME" ]; then
            echo "cname_exists=true" >> $GITHUB_OUTPUT
          else
            echo "cname_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build
        env:
          BASE_PATH: ${{ steps.check-cname.outputs.cname_exists == 'true' && '' || format('/{0}', github.event.repository.name) }}
        run: |
          npm run build

      - name: Copy CNAME file to build directory if it exists
        if: steps.check-cname.outputs.cname_exists == 'true'
        run: |
          cp CNAME build/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
